defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:8

commands:
  npmrc:
    description: Create NPM credentials file
    steps:
      - run:
          name: Create NPM credentials file
          command: echo -e $NPMRC > ~/.npmrc

version: 2.1
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - npmrc
      - run:
          name: Install dependencies
          command: "[ -d node_modules ] || npm i"
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm t
      - run:
          name: Code linting
          command: npm run lint -- --plugin log
  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - npmrc
      - run:
          name: Publish to NPM
          command: npm start
  docs:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create a webpage from the readme
          command: npx markt --source README.md --destination ./gh-pages/index.html --preset plain --title "published - Opinionated NPM publish program" --description "published helps streamline a git based workflow with package publishing through continues delivery. Developers control their branch and version strategies, and published takes care of logical conditioning of when to publish stable versions and/or release candidates."
      - run:
          name: Set git user
          command: curl ci-cd.net/v1/git/user | sh -s a1vy a01101100vy@gmail.com
      - run:
          name: Push gh-pages
          command: curl ci-cd.net/v1/gh/pages | sh -s gh-pages/.
  glossary:
    <<: *defaults
    steps:
      - run:
          name: Add to Glossary
          command: |
            curl --user ${CIRCLECI_API_TOKEN}: \
              --header "Content-Type: application/json" \
              --data "{\"build_parameters\":{\"TRIGGERING_REPOSITORY\":\"${CIRCLE_REPOSITORY_URL}\"}}" \
              --request POST \
              https://circleci.com/api/v1.1/project/github/fiverr/glossary/tree/master

experimental:
  notify:
    branches:
      only:
        - master

workflows:
  version: 2.1
  ci-cd:
    jobs:
      - install:
          context: org-global
      - test:
          requires:
            - install
      - publish:
          context: org-global
          requires:
            - test
      - docs:
          filters:
            branches:
              only:
                - master
          requires:
            - test
      - glossary:
          filters:
            branches:
              only:
                - master
          requires:
            - publish
